### ISSUE TITLE
failure to optimise a json file in minecraft 1.19.3

### ISSUE THREAD

**Issue by eristhea** [P03W/Machete#6]
```
[lily@lily-desktop rainglow]$ gradle build

> Configure project :
Fabric Loom: 1.0.17

> Task :optimizeOutputsOfShadowJar
Failed to optimize data/minecraft/worldgen/density_function/zero.json
io.github.p03w.machete.core.libs.json.JsonFormatError: Unrecognized starting character "0"
        at io.github.p03w.machete.core.libs.json.JsonMinifier.parse(JsonMinifier.kt:21)
        at io.github.p03w.machete.core.libs.json.JsonMinifier.<init>(JsonMinifier.kt:13)
        at io.github.p03w.machete.core.passes.JsonPass.processFile(JsonPass.kt:22)
        at io.github.p03w.machete.core.JarOptimizer.optimize(JarOptimizer.kt:74)
        at io.github.p03w.machete.tasks.OptimizeJarsTask.optimizeJars(OptimizeJarsTask.kt:29)
```

can be reproduced by running `gradle build` on my project [rainglow](https://github.com/ix0rai/rainglow) at [this revision](https://github.com/ix0rai/rainglow/tree/685d3efd5bf185b5b5659fdfae279715569a3ce3)
tested with machete `2.0.0`

**Comment by SilverAndro** [comment]
how bizarre, something youve got is outputting a .json file thats (i assume) just `0`, which definitely isnt valid json

ill take a look later but im surprised that works in MC

**Comment by eristhea** [comment]
I should have looked at the file itself :p
this is it:
```
0.0
```

**Comment by SilverAndro** [comment]
well that would certainly do it! haha 🥳
